server.port: 8090
spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gestionBiblioP7
    username: postgres
    password: floDU1716
  jpa:
    hibernate:
      ddl-auto: create-drop # When you launch the application for the first time - switch "none" at "create"
      spring:
    show-sql: true
jwt.secret: marseille

spring.mail.host: smtp.office365.com
spring.mail.port: 587
spring.mail.username: <username>
spring.mail.password: <password>
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.transport.protocol: smtp
